//! Modifier system: apply, remove, and manage duration of card modifiers.

use crate::effect::{AppliedModifier, Modifier, ModifierDuration};
use crate::state::{CardInstance, CoreGameEvent, GameState};
use crate::types::{CardType, InstanceId, PlayerId, Property};

/// Reason for checking immunity.
#[derive(Debug, Clone, PartialEq)]
pub enum ImmunityCheck {
    /// Immune to effects from cards of this type
    ByCardType(CardType),
    /// Immune to effects from cards with this property
    ByProperty(Property),
    /// Immune to destruction effects
    Destruction,
    /// Immune to being targeted
    Targeting,
}

/// Stateless modifier manager.
pub struct ModifierManager;

impl ModifierManager {
    /// Apply a modifier to a card instance.
    ///
    /// If the modifier is `AttackBoost(delta)`, immediately adjusts `current_attack`.
    pub fn apply_modifier(
        card: &mut CardInstance,
        modifier: Modifier,
        source: InstanceId,
        duration: ModifierDuration,
    ) {
        if let Modifier::AttackBoost(delta) = &modifier
            && let Some(atk) = card.current_attack.as_mut()
        {
            *atk += *delta as i32;
            if *atk < 0 {
                *atk = 0;
            }
        }

        card.modifiers.push(AppliedModifier {
            modifier,
            source,
            duration,
        });
    }

    /// Remove a modifier at the given index from a card.
    ///
    /// If the modifier was `AttackBoost(delta)`, reverts the attack change.
    pub fn remove_modifier(card: &mut CardInstance, index: usize) {
        if index >= card.modifiers.len() {
            return;
        }

        let applied = card.modifiers.remove(index);

        if let Modifier::AttackBoost(delta) = &applied.modifier
            && let Some(atk) = card.current_attack.as_mut()
        {
            *atk -= *delta as i32;
            if *atk < 0 {
                *atk = 0;
            }
        }
    }

    /// Clean up expired modifiers across all cards in the game state.
    ///
    /// Called at TurnEnd. Returns events generated by cleanup (e.g., attack changes).
    pub fn cleanup_expired(state: &mut GameState) -> Vec<CoreGameEvent> {
        let events = Vec::new();

        for player_idx in 0..2 {
            let player_id = if player_idx == 0 {
                PlayerId::Player1
            } else {
                PlayerId::Player2
            };

            for slot in 0..5 {
                if state.players[player_idx].zones.front[slot].is_none() {
                    continue;
                }
                let indices_to_remove = Self::find_expired_indices(
                    state.players[player_idx].zones.front[slot]
                        .as_ref()
                        .unwrap(),
                    state,
                    player_id,
                );
                let card_mut = state.players[player_idx].zones.front[slot]
                    .as_mut()
                    .unwrap();
                for &idx in indices_to_remove.iter().rev() {
                    Self::remove_modifier(card_mut, idx);
                }
            }

            for slot in 0..5 {
                if state.players[player_idx].zones.back[slot].is_none() {
                    continue;
                }
                let indices_to_remove = Self::find_expired_indices(
                    state.players[player_idx].zones.back[slot].as_ref().unwrap(),
                    state,
                    player_id,
                );
                let card_mut = state.players[player_idx].zones.back[slot].as_mut().unwrap();
                for &idx in indices_to_remove.iter().rev() {
                    Self::remove_modifier(card_mut, idx);
                }
            }
        }

        events
    }

    /// Find indices of modifiers that should be removed from a card.
    fn find_expired_indices(
        card: &CardInstance,
        state: &GameState,
        _player: PlayerId,
    ) -> Vec<usize> {
        let mut to_remove = Vec::new();

        for (idx, applied) in card.modifiers.iter().enumerate() {
            let expired = match &applied.duration {
                ModifierDuration::Permanent => false,
                ModifierDuration::UntilEndOfTurn => true,
                ModifierDuration::TurnCount(n) => *n == 0,
                ModifierDuration::WhileSourceOnField => !Self::is_on_field(state, applied.source),
            };
            if expired {
                to_remove.push(idx);
            }
        }

        to_remove
    }

    /// Decrement TurnCount modifiers (call at start of each turn).
    pub fn decrement_turn_counts(state: &mut GameState) {
        for player_idx in 0..2 {
            for slot in 0..5 {
                if let Some(card) = state.players[player_idx].zones.front[slot].as_mut() {
                    for applied in card.modifiers.iter_mut() {
                        if let ModifierDuration::TurnCount(ref mut n) = applied.duration
                            && *n > 0
                        {
                            *n -= 1;
                        }
                    }
                }
                if let Some(card) = state.players[player_idx].zones.back[slot].as_mut() {
                    for applied in card.modifiers.iter_mut() {
                        if let ModifierDuration::TurnCount(ref mut n) = applied.duration
                            && *n > 0
                        {
                            *n -= 1;
                        }
                    }
                }
            }
        }
    }

    /// Check if a card has immunity matching the given check.
    pub fn has_immunity(card: &CardInstance, check: &ImmunityCheck) -> bool {
        card.modifiers
            .iter()
            .any(|applied| match (&applied.modifier, check) {
                (Modifier::ImmuneToCardType(ct), ImmunityCheck::ByCardType(check_ct)) => {
                    ct == check_ct
                }
                (Modifier::ImmuneToProperty(p), ImmunityCheck::ByProperty(check_p)) => p == check_p,
                (Modifier::ImmuneToDestruction, ImmunityCheck::Destruction) => true,
                (Modifier::ImmuneToTargeting, ImmunityCheck::Targeting) => true,
                _ => false,
            })
    }

    /// Get the effective attack power of a card (base + all AttackBoost modifiers).
    ///
    /// Returns 0 if the card has no attack (non-character cards).
    pub fn get_effective_attack(card: &CardInstance) -> i32 {
        card.current_attack.unwrap_or(0).max(0)
    }

    /// Check if a card instance is currently on the field (front or back zone).
    fn is_on_field(state: &GameState, instance_id: InstanceId) -> bool {
        for player in &state.players {
            if player
                .zones
                .front
                .iter()
                .flatten()
                .any(|c| c.instance_id == instance_id)
            {
                return true;
            }
            if player
                .zones
                .back
                .iter()
                .flatten()
                .any(|c| c.instance_id == instance_id)
            {
                return true;
            }
        }
        false
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::effect::{Modifier, ModifierDuration};
    use crate::rules::GameRules;
    use crate::state::{CardInstance, GameState};
    use crate::types::{CardId, CardType, InstanceId};

    fn test_card(id: u32, attack: i32) -> CardInstance {
        CardInstance::new(InstanceId(id), CardId::new("S000-C-001"), Some(attack))
    }

    #[test]
    fn test_apply_attack_boost() {
        let mut card = test_card(1, 500);
        ModifierManager::apply_modifier(
            &mut card,
            Modifier::AttackBoost(200),
            InstanceId(99),
            ModifierDuration::UntilEndOfTurn,
        );
        assert_eq!(card.current_attack, Some(700));
        assert_eq!(card.modifiers.len(), 1);
    }

    #[test]
    fn test_remove_attack_boost_reverts() {
        let mut card = test_card(1, 500);
        ModifierManager::apply_modifier(
            &mut card,
            Modifier::AttackBoost(200),
            InstanceId(99),
            ModifierDuration::UntilEndOfTurn,
        );
        assert_eq!(card.current_attack, Some(700));
        ModifierManager::remove_modifier(&mut card, 0);
        assert_eq!(card.current_attack, Some(500));
        assert_eq!(card.modifiers.len(), 0);
    }

    #[test]
    fn test_attack_boost_clamps_to_zero() {
        let mut card = test_card(1, 100);
        ModifierManager::apply_modifier(
            &mut card,
            Modifier::AttackBoost(-500),
            InstanceId(99),
            ModifierDuration::Permanent,
        );
        assert_eq!(card.current_attack, Some(0));
    }

    #[test]
    fn test_cleanup_until_end_of_turn() {
        let mut state = GameState::new(GameRules::default(), 42);
        let mut card = test_card(1, 500);
        ModifierManager::apply_modifier(
            &mut card,
            Modifier::AttackBoost(200),
            InstanceId(99),
            ModifierDuration::UntilEndOfTurn,
        );
        state.players[0].zones.front[0] = Some(card);

        ModifierManager::cleanup_expired(&mut state);

        let card_after = state.players[0].zones.front[0].as_ref().unwrap();
        assert_eq!(card_after.modifiers.len(), 0);
        assert_eq!(card_after.current_attack, Some(500));
    }

    #[test]
    fn test_permanent_modifier_not_cleaned() {
        let mut state = GameState::new(GameRules::default(), 42);
        let mut card = test_card(1, 500);
        ModifierManager::apply_modifier(
            &mut card,
            Modifier::AttackBoost(100),
            InstanceId(99),
            ModifierDuration::Permanent,
        );
        state.players[0].zones.front[0] = Some(card);

        ModifierManager::cleanup_expired(&mut state);

        let card_after = state.players[0].zones.front[0].as_ref().unwrap();
        assert_eq!(card_after.modifiers.len(), 1);
        assert_eq!(card_after.current_attack, Some(600));
    }

    #[test]
    fn test_while_source_on_field_cleanup() {
        let mut state = GameState::new(GameRules::default(), 42);
        let source_id = InstanceId(99);
        let mut card = test_card(1, 500);
        ModifierManager::apply_modifier(
            &mut card,
            Modifier::AttackBoost(100),
            source_id,
            ModifierDuration::WhileSourceOnField,
        );
        state.players[0].zones.front[0] = Some(card);
        ModifierManager::cleanup_expired(&mut state);

        let card_after = state.players[0].zones.front[0].as_ref().unwrap();
        assert_eq!(card_after.modifiers.len(), 0);
        assert_eq!(card_after.current_attack, Some(500));
    }

    #[test]
    fn test_while_source_on_field_kept_when_present() {
        let mut state = GameState::new(GameRules::default(), 42);
        let source_id = InstanceId(99);
        let source_card = test_card(99, 300);
        let mut target_card = test_card(1, 500);
        ModifierManager::apply_modifier(
            &mut target_card,
            Modifier::AttackBoost(100),
            source_id,
            ModifierDuration::WhileSourceOnField,
        );
        state.players[0].zones.front[0] = Some(target_card);
        state.players[0].zones.front[1] = Some(source_card);

        ModifierManager::cleanup_expired(&mut state);

        let card_after = state.players[0].zones.front[0].as_ref().unwrap();
        assert_eq!(card_after.modifiers.len(), 1);
        assert_eq!(card_after.current_attack, Some(600));
    }

    #[test]
    fn test_has_immunity_destruction() {
        let mut card = test_card(1, 500);
        ModifierManager::apply_modifier(
            &mut card,
            Modifier::ImmuneToDestruction,
            InstanceId(99),
            ModifierDuration::Permanent,
        );
        assert!(ModifierManager::has_immunity(
            &card,
            &ImmunityCheck::Destruction
        ));
        assert!(!ModifierManager::has_immunity(
            &card,
            &ImmunityCheck::Targeting
        ));
    }

    #[test]
    fn test_has_immunity_by_card_type() {
        let mut card = test_card(1, 500);
        ModifierManager::apply_modifier(
            &mut card,
            Modifier::ImmuneToCardType(CardType::Strategy),
            InstanceId(99),
            ModifierDuration::Permanent,
        );
        assert!(ModifierManager::has_immunity(
            &card,
            &ImmunityCheck::ByCardType(CardType::Strategy)
        ));
        assert!(!ModifierManager::has_immunity(
            &card,
            &ImmunityCheck::ByCardType(CardType::Item)
        ));
    }

    #[test]
    fn test_get_effective_attack() {
        let card = test_card(1, 500);
        assert_eq!(ModifierManager::get_effective_attack(&card), 500);
    }

    #[test]
    fn test_get_effective_attack_no_attack() {
        let card = CardInstance::new(InstanceId(1), CardId::new("S000-S-001"), None);
        assert_eq!(ModifierManager::get_effective_attack(&card), 0);
    }
}
