[package]
name = "card-bevy"
edition.workspace = true
version.workspace = true

[[bin]]
name = "card-bevy"
path = "src/main.rs"

[dependencies]
bevy = { version = "0.18", features = ["wayland"] }
bevy_simple_text_input = "0.14"
card-core = { path = "../card-core" }
card-client = { path = "../card-client" }
