[package]
name = "card-bevy"
edition.workspace = true
version.workspace = true

[[bin]]
name = "card-bevy"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
bevy = { version = "0.18", features = ["wayland"] }
bevy_simple_text_input = "0.14"
card-core = { path = "../card-core" }
card-client = { path = "../card-client" }
card-script = { path = "../card-script" }
card-server = { path = "../card-server" }
tokio = { workspace = true }
